docs: Redirect deprecated Documentation URLs to the current Github ones
mcu-tools/website-mcuboot pull request #22
Opened 2022-05-24 20:25 UTC by almir-okato

Some external MCUboot tutorials and posts still have the old URL reference for documentation and they are not up to date. 
This PR makes the redirection of these URL to the actual documentation pages.

2022-05-24 20:27 UTC, almir-okato commented
@d3zd3z @kylekirkby PTAL

2022-05-24 20:46 UTC, d3zd3z requested changes
Otherwise, looks good. This will help people stop getting the old docs.

2022-05-24 20:46 UTC, d3zd3z commented on Gemfile
> +    gem "jekyll-redirect-from"
Missing newline at the end of the file.

2022-05-25 06:50 UTC, kylekirkby commented
Hi @almir-okato ,

I'm sorry but we already have a mechanism in place for adding redirects to our Jekyll sites

https://github.com/mcu-tools/website-mcuboot/blob/main/_data/routingrules.json

Please add your redirects to this file.

These redirects will then be deployed via lambda@edge.

Cheers!

Kyle

2022-05-25 13:06 UTC, kylekirkby commented
> @kylekirkby I tried to use this file, however it didn't work, and I could not find how to properly do that using the file. Could you please provide an example?

Hi @almir-okato ,

So for `/documentation/SECURITY/` (_documentation/SECURITY.md) add a line like:

```
  "^/documentation/SECURITY(/?|/index.html)$ https://docs.mcuboot.com/SECURITY  [R,L,NC]",
```

You can see the `routingrules.json` for the Linaro.org website, which is using the same website build stack, here: 

https://github.com/Linaro/website/blob/master/_data/routingrules.json

2022-05-25 18:38 UTC, almir-okato commented
Hi @kylekirkby 
I did as you said, however the link checking job is failing, do you have any suggestions on what could be missing or wrong?
Thanks!

2022-06-07 08:21 UTC, kylekirkby commented
Hi @almir-okato,

The failed twitter links were due to an issue with the Link Checker script / Twitter, I've re-run the failed GH jobs and the checks have passed. Apologies about this! 

Cheers,

Kyle

2022-06-07 14:53 UTC, almir-okato commented
Hi @kylekirkby, thank you!
Would be possible to merge?

2022-06-07 15:00 UTC, kylekirkby approved these changes

2022-06-07 15:02 UTC, kylekirkby requested changes
Do we not want to keep these old documentation redirects in the file?

It may be a good idea for legacy links?

2022-06-07 15:02 UTC, kylekirkby commented
> Do we not want to keep these old documentation redirects in the file?
> 
> It may be a good idea for legacy links?

If not, then it looks good to me :)

2022-06-07 15:15 UTC, almir-okato commented
> Do we not want to keep these old documentation redirects in the file?
> 
> It may be a good idea for legacy links?

Did you mean that we need to remove the deprecated pages files from repo?

2022-06-08 08:50 UTC, kylekirkby commented
> > Do we not want to keep these old documentation redirects in the file?
> > It may be a good idea for legacy links?
> 
> Did you mean that we need to remove the deprecated pages files from repo?

I mean the old redirects that you've replaced e.g:

```
  "^/release-notes.html$ /documentation/release-notes/ [R,L,NC]",
```
It might be worth keeping these and updating them to point to the new locations?

2022-06-08 13:04 UTC, kylekirkby approved these changes

2022-06-08 15:08 UTC, almir-okato commented
@d3zd3z could you please take a look again?
Thanks!

2022-07-21 12:58 UTC, almir-okato commented
@d3zd3z could you please take a look again? Its pending for merging.
Thanks!

2022-09-20 22:32 UTC, d3zd3z approved these changes

2022-09-23 07:22 UTC, merged